name: Cypress Tests GitHub Actions Pipeline
run-name: Run Cypress tests - Done by @${{ github.actor }}

on:
  schedule:
    - cron: '0 0 * * 5'  # Every Friday at midnight (00:00)
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CYPRESS_BASE_URL: ${{ vars.BASE_URL }}
  CYPRESS_PASSWORD: ${{ secrets.PASSWORD }}
  CYPRESS_USERNAME: ${{ secrets.USERNAME }}
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_CLOUD_KEY }}

jobs:
  cypress-run-login:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: true
          env: grep=@Login
    

  cypress-run-smoke:
    runs-on: ubuntu-22.04
    needs: cypress-run-login
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: true
          env: grep=@Smoke

  cypress-run-regression:
    runs-on: ubuntu-22.04
    needs: cypress-run-smoke
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: true
          env: grep=@Regression


#The next job is here as an example, but is never gonna execute
  cypress-run-directly-with-node:
    if: github.repository == 'nonexistent/branch'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm ci
      - run: npm run cy:run
